name: Publish

on:
  push:
    tags:
      - "*"

jobs:
  publish:
    name: Publish binaries
    runs-on: macos-latest

    steps:
    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: FreshchatSDK.xcframework.zip
        asset_name: FreshchatSDK.xcframework.zip
        tag: ${{ github.ref }}
        overwrite: true