# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Swift

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    - name: Clone original repo
      run: git clone https://github.com/freshworks/freshchat-ios.git
    - name: Create zip
      run: cd freshchat-ios && zip -r FreshchatSDK.xcframework.zip FreshchatSDK.xcframework
    - name: Compute checksum
      run: swift package compute-checksum FreshchatSDK.xcframework.zip > checksum.txt
    - name: Edit Package.swift
      run: 'export CHECKSUM=$(cat checksum.txt) && sed -E "s/checksum: \".+\"/checksum: \"$CHECKSUM\"/g" Package.swift'
